version: 2.1
orbs:
  azure-acr: circleci/azure-acr@0.1.4
  ms-teams: cloudradar-monitoring/ms-teams@0.0.1
jobs:
  test:
    docker:
      - image: cimg/python:3.9
        environment:
          DATABASE_HOST: localhost
          DATABASE_PORT: 5432

      - image: postgres:12-alpine
        environment:
          POSTGRES_USER: dhos-reporting
          POSTGRES_PASSWORD: TopSecretPassword
          POSTGRES_DB: "dhos-reporting"
    steps:
      - checkout
      - run:
          name: Create coverage report dir
          command: mkdir -p ${COVERAGE_REPORT_DIR}
      - run: |
          poetry self update
          poetry config http-basic.sensynehealth ${GEMFURY_DOWNLOAD_KEY} ''
          pip install --upgrade tox
      - run:
          name: Create tox environment
          command: tox -e poetry-install
      - restore_cache:
          keys:
            - v1-poetry-deps-{{ checksum "poetry.lock" }}
            - v1-poetry-deps-
      - run:
          name: Run tox tests
          command: tox -e py39
      - save_cache:
          key: v1-poetry-deps-{{ checksum "poetry.lock" }}
          paths:
            - .tox
      - persist_to_workspace:
          root: coverage-reports
          paths:
            - coverage.xml
  integration-test:
    docker:
      - image: sensynehealth.azurecr.io/she/circleci-build-image:latest
        auth:
          username: $AZURE_SENSYNEHEALTH_ACR_ADMIN_USER
          password: $AZURE_SENSYNEHEALTH_ACR_ADMIN_USER_PASSWORD
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
          version: 20.10.7
      - run:
          name: Auth with ACR
          command: source /usr/local/bin/deployment-helpers-v1.sh; authenticateToACR
      - run:
          name: Run the integration test script
          command: .circleci/run_integration_tests.sh
  deploy-dev:
    docker:
      - image: sensynehealth.azurecr.io/she/circleci-build-image:latest
        auth:
          username: $AZURE_SENSYNEHEALTH_ACR_ADMIN_USER
          password: $AZURE_SENSYNEHEALTH_ACR_ADMIN_USER_PASSWORD
    environment:
      K8S_DEV_DEPLOYMENT_NAME: deployment/dhos-reporting-api-dep
      ACR_REPO_BASE: dhos
      TYK_PORTAL_API_NAME: DHOS REPORTING API
      TYK_PORTAL_OPENAPI_YAML_PATH: dhos_reporting_api/openapi/openapi.yaml
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Add build information
          command: .circleci/record_build_info.sh
      - azure-acr/build-and-push-image:
          checkout: false
          login-server-name: ${AZURE_LOGIN_SERVER_NAME}
          registry-name: ${AZURE_REGISTRY_NAME}
          repo: ${ACR_REPO_BASE}/dhos-reporting-api
          tag: dev,cb-${CIRCLE_BUILD_NUM},$(git log --pretty=format:'%h' -n 1)
          extra-build-args: --build-arg GEMFURY_DOWNLOAD_KEY
      - run:
          name: Deploy to UK dev cluster in Azure
          command: .circleci/deploy_azure_dev.sh uk uk-dev-api-upstream
      - ms-teams/report:
          only_on_fail: true
          webhook_url: ${MSTEAMS_NOTIFY_WEBHOOK_URL}
workflows:
  version: 2
  build_test_deploy:
    jobs:
      - test:
          context: engineering-build
      - integration-test:
          context: engineering-build
      - deploy-dev:
          context: dhos-deploy
          requires:
            - test
            - integration-test
          filters:
            branches:
              only:
                - develop
